server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  include /etc/nginx/mime.types;
  default_type application/octet-stream;
  charset utf-8;

  # compresión
  gzip on;
  gzip_types text/plain text/css application/json application/javascript application/xhtml+xml application/xml image/svg+xml;
  gzip_min_length 1024;

  # Assets con hash: cache agresivo
  location ~* \.(?:js|css|png|jpg|jpeg|gif|svg|ico|woff2?|ttf|eot|webp|avif|map)$ {
    try_files $uri =404;
    expires 1y;
    add_header Cache-Control "public, immutable";
  }

  # NO cache para index.html (y archivos de control de PWA)
  location = /index.html {
    try_files $uri =404;
    add_header Cache-Control "no-store, must-revalidate" always;
    expires -1;
  }
  location = /ngsw.json {
    try_files $uri =404;
    add_header Cache-Control "no-store, must-revalidate" always;
    expires -1;
  }
  location = /manifest.webmanifest {
    try_files $uri =404;
    add_header Cache-Control "no-store, must-revalidate" always;
    expires -1;
  }

  # SPA fallback: rutas de app -> index.html
  location / {
    try_files $uri $uri/ /index.html;
  }
}